name: como_gasto
description: An app to help to track your expenses

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.8.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+4
  uuid:
  local_auth: ^0.6.2+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  google_sign_in: ^4.5.1
#  flutter_twitter_login: ^1.1.0
  #flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1
  shared_preferences: ^0.5.8
  rect_getter: ^0.1.0
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.4.4+2
  datetime_picker_formfield: ^1.0.0
  flare_flutter: ^2.0.5
  yaml: ^2.2.0
  flutter_hooks: ^0.11.0
  get_it: ^4.0.2

dev_dependencies:
  test:
  mockito:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon_base.png"
  image_path_ios: "assets/launcher_icon_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  ComoGastoIcons
      fonts:
      - asset: assets/ComoGastoIcons.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
